ci_access:
  groups:
    - id: dh-go-backend
    
  # #- id: gitlab-org/cluster-integration/gitlab-agent
  # - id: dh-go-backend/dh-backend/dh-backend-user-sv
  #   #default_namespace: dh-backend
  #   paths:
  #     # Read all YAML files from base directory.
  #   - glob: '.manifests/base/*.{yaml,yml,json}'
  #     # Read all .yaml files from team2/apps and all subdirectories.
  #   - glob: '.manifests/overlays/dev/*.{yaml,yml,json}'
  #   #- glob: '.manifests/overlays/pre/*.{yaml,yml,json}'
  #   #- glob: '.manifests/overlays/qa/*.{yaml,yml,json}'
  #     # If 'paths' is not specified or is an empty list, the configuration below is used.
  #   # - glob: '/**/*.{yaml,yml,json}'
  #   reconcile_timeout: 3600s
  #   dry_run_strategy: none
  #   prune: true
  #   prune_timeout: 3600s
  #   prune_propagation_policy: foreground
  #   inventory_policy: must_match
